### ISSUE TITLE
Stand-alone Build does not seem to work

### ISSUE THREAD

**Issue by vifino** [ReadyTalk/avian#395]
Hello.
I have trouble getting the non-dynamic build with the OpenJDK to work.

```
$ ./avian -jar ~/jruby/jruby.jar
java/lang/UnsatisfiedLinkError: library not found in /usr/lib/jvm/java-7-openjdk/jre/lib/amd64:/usr/lib/jvm/java-7-openjdk/jre/lib/amd64/xawt: libverify.so
```

After looking at the directory in the above error message, I found libverify.so without a problem.
I compiled Avian with `make openjdk=/usr/lib/jvm/java-7-openjdk openjdk_source=/usr/lib/jvm/java-7-openjdk/src`.
This takes place in the build output directory ( aka build/linux-x86_64-openjdk )
I am running Arch Linux, x86_64.

Greetings,
vifino

**Comment by joshuawarner32** [comment]
I think your problem is misspelling the `openjdk-src` flag.  Without that, you'll be doing a build that still depends on the installed openjdk libraries.

Did you see it spelled `openjdk_source` somewhere in the documentation?  If so, we should update that.

**Comment by dicej** [comment]
Even if openjdk-src is spelled correctly, it still won't work if the app uses AWT, as discussed here:

https://groups.google.com/forum/#!topic/avian/DI8M8Jh4InI

**Comment by vifino** [comment]
Thank you very much @joshuawarner32.
I read that *somewhere* but I do not remember where, sorry.

Greetings,
vifino

**Comment by vifino** [comment]
Okay, after I moved the build to another machine and test it, I got the same error again.
I only copied 'avian' ( With the working standalone build ) to my server. Runs Arch Linux too, even has the same jvm installed.

Greetings,
vifino

**Comment by dicej** [comment]
@vifino, did you see my comment about AWT above?

**Comment by vifino** [comment]
@dicej Yes I did, but I just did `avian -V`, which even showed that up.

**Comment by dicej** [comment]
Did you copy avian from build/linux-x86_64-openjdk/ or from build/linux-x86_64-openjdk-src/?  It should be the latter.

Meanwhile, I'll try to reproduce this on my side.

**Comment by vifino** [comment]
I copied avian from build/linux-x86_64-tails-openjdk.
I compiled the build above with `make openjdk=/usr/lib/jvm/java-7-openjdk openjdk_src=/usr/lib/jvm/java-7-openjdk/src/ tails=true`, no `-src` there at all.
The avian binary works fine on my local system, but does not work on another system, even though it runs the same OS, same libraries, etc..

Greetings,
vifino

**Comment by dicej** [comment]
It should be openjdk-src=... as documented here:

https://github.com/ReadyTalk/avian/blob/master/README.md#building-with-the-openjdk-class-library

That will produce a binary under build/linux-x86_64-tails-openjdk-src.

**Comment by vifino** [comment]
Okay, this was definitly my fault then.
But now, I can't get it to build and I suppose that this is not a typo:
```
$ make openjdk=/usr/lib/jvm/java-7-openjdk openjdk-src=/usr/lib/jvm/java-7-openjdk/src tails=true                                                                                                             
find: `/usr/lib/jvm/java-7-openjdk/src/solaris/native/common': No such file or directory
find: `/usr/lib/jvm/java-7-openjdk/src/solaris/native/common': No such file or directory
find: `/usr/lib/jvm/java-7-openjdk/src/solaris/native/common': No such file or directory
find: `/usr/lib/jvm/java-7-openjdk/src/solaris/native/common': No such file or directory
compiling build/linux-x86_64-tails-openjdk-src/system/posix.o
compiling build/linux-x86_64-tails-openjdk-src/system/posix/signal.o
compiling build/linux-x86_64-tails-openjdk-src/system/posix/crash.o
compiling build/linux-x86_64-tails-openjdk-src/system/posix/memory.o
compiling build/linux-x86_64-tails-openjdk-src/finder.o
compiling build/linux-x86_64-tails-openjdk-src/machine.o
compiling build/linux-x86_64-tails-openjdk-src/util.o
compiling build/linux-x86_64-tails-openjdk-src/heap/heap.o
compiling build/linux-x86_64-tails-openjdk-src/compile.o
compiling build/linux-x86_64-tails-openjdk-src/classpath-openjdk.o
compiling build/linux-x86_64-tails-openjdk-src/builtin.o
compiling build/linux-x86_64-tails-openjdk-src/jnienv.o
compiling build/linux-x86_64-tails-openjdk-src/process.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/compiler.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/compiler/event.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/compiler/ir.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/compiler/frame.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/compiler/value.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/compiler/read.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/compiler/site.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/compiler/resource.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/compiler/regalloc.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/compiler/promise.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/compiler/context.o
compiling build/linux-x86_64-tails-openjdk-src/debug-util.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/runtime.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/targets.o
compiling build/linux-x86_64-tails-openjdk-src/util/fixed-allocator.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/target/x86/assembler.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/target/x86/multimethod.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/target/x86/detect.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/target/x86/block.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/target/x86/fixup.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/target/x86/encode.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/target/x86/operations.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/target/x86/context.o
compiling build/linux-x86_64-tails-openjdk-src/codegen/target/x86/padding.o
compiling build/linux-x86_64-tails-openjdk-src/x86_64-asm.o
compiling build/linux-x86_64-tails-openjdk-src/compile-x86_64-asm.o
make: *** No rule to make target '/usr/lib/jvm/java-7-openjdk/src/share/native/common/check_code.c', needed by 'build/linux-x86_64-tails-openjdk-src/openjdk/share/native/common/check_code-openjdk.o'.  Stop.
```

Greetings,
vifino

**Comment by joshuawarner32** [comment]
My suspicion would be you're not pointing openjdk-src to the correct directory.  There will be multiple `src` directories in the openjdk source code, and as I recall, the one directly at the root is not the correct one.

You could search for candidates with `find /usr/lib/jvm/java-7-openjdk -path solaris/native/common`, and then pick the directory above `solaris` as the argument to `openjdk-src`.

**Comment by vifino** [comment]
I tried many things ( including trying to build the jdk from source, which errored, and does not seem to be related to me ) but nothing works.
`find /usr/lib/jvm/java-7-openjdk -path solaris/native/common` returns nothing, every openjdkX-src package does not include any folder like that.
Trying to build the jdk manually got me a bit farther but not by much. The jdk build failed because the makefile contains syntax errors.

I have no clue anymore.

Greetings,
vifino

**Comment by joshuawarner32** [comment]
Those are probably not "real" source packages, then - but rather classpath source packages.  Avian needs the native code sources.

Your best bet might be to check out the official source tree (hg.openjdk.java.net/jdk7u/jdk7u60/), which will definitely have those paths.

**Comment by dicej** [comment]
I've never used Arch, but it looks like the openjdk7-src package only includes src.zip, i.e. the .java source files for the OpenJDK class library.  The Avian openjdk-src package also needs the .c native source code.  On Debian, you'd get that by using "apt-get source openjdk-7-jdk"; I don't know what the equivalent is for Arch.

If you're having a hard time building the JDK from source, you might want to just grab a prebuilt copy from https://github.com/alexkasko/openjdk-unofficial-builds along with the corresponding source.  Alternatively, the build system for JDK 8 has been greatly improved, so you might want to try building that.  We haven't done a lot of testing with Avian and JDK 8 yet, but we'll try to fix any bugs you find.

**Comment by dicej** [comment]
Caveat regarding @joshuawarner32's last comment: make sure the source tree you're using for the openjdk-src=... option corresponds to the binary tree you're using for the openjdk=... option.  The Arch build may have patches that aren't included in the upstream source from java.net.

**Comment by vifino** [comment]
Okay, a friend and myself are trying to get https://github.com/alexkasko/openjdk-unofficial-builds running, and if that does not work, we will try JDK 8.

**Comment by vifino** [comment]
Okay, we got somewhere, now we both don't know any further.
We have no clue where jvm.h is.

```
build/linux-x86_64-tails-openjdk-src/openjdk/check_code.c:89:17: fatal error: jvm.h: No such file or directory
 #include "jvm.h"
```

**Comment by dicej** [comment]
Can you tell me the URLs of the OpenJDK source and binary packages, plus the command you're using to build Avian?  I'll try to reproduce it on my machine.

**Comment by vifino** [comment]
We cloned http://hg.openjdk.java.net/jdk7u/jdk7u/ as the source.
We used the build from https://github.com/alexkasko/openjdk-unofficial-builds, which is https://bitbucket.org/alexkasko/openjdk-unofficial-builds/downloads/openjdk-1.7.0-u60-unofficial-linux-amd64-image.zip

**Comment by dicej** [comment]
Here's what I did:

```
hg clone http://hg.openjdk.java.net/jdk7u/jdk7u60/
cd jdk7u60/
bash get_source.sh 
cd ..
wget https://bitbucket.org/alexkasko/openjdk-unofficial-builds/downloads/openjdk-1.7.0-u60-unofficial-linux-amd64-image.zip
unzip openjdk-1.7.0-u60-unofficial-linux-amd64-image.zip 
git clone https://github.com/readytalk/avian
cd avian/
make openjdk=$(pwd)/../openjdk-1.7.0-u60-unofficial-linux-amd64-image openjdk-src=$(pwd)/../jdk7u60/jdk/src tails=true test
```

Does that work for you?  It's working for me.

**Comment by vifino** [comment]
Looked very promising until this...
```
In file included from src/main.cpp:14:0:
/usr/lib/jvm/openjdk-7-u60/include/jni.h:45:20: fatal error: jni_md.h: No such file or directory
 #include "jni_md.h"
```

This was definitly further than we came.

**Comment by dicej** [comment]
Try setting JAVA_HOME to the downloaded JDK directory, e.g.:

```
export JAVA_HOME=$(pwd)/../openjdk-1.7.0-u60-unofficial-linux-amd64-image
```

**Comment by vifino** [comment]
Wonderful! It worked!
Thank you very, very much, @dicej!

Greetings,
vifino

**Comment by meiravdean** [comment]
Hi, 

I came across the same issue as vifino and did the exact steps as written w/ the following differences: the folder openjdk-src is directed to $(pwd)/../jdk7u60/jaxp/src instead of openjdk-src=$(pwd)/../jdk7u60/jdk/src hence the full compilation command is:

make openjdk=$(pwd)/../openjdk-1.7.0-u60-unofficial-linux-amd64-image openjdk-src=$(pwd)/../jdk7u60/jaxp/src tails=true test

still, at the end of the compilation i'm having the following the error:

make: *** No rule to make target `/home/dorons/Meirav/test2/avian/../jdk7u60/jaxp/src/share/native/common/check_code.c', needed by `build/linux-x86_64-tails-openjdk-src/openjdk/share/native/common/check_code-openjdk.o'.  Stop.

**Comment by joshuawarner32** [comment]
@meiravdean - I'm guessing the problem is that you're using the wrong path for openjdk-src.  Do a `find /home/dorons/Meirav/test2/avian/../jdk7u60/ -name check_code.c`, and use the results to adjust the openjdk-src path you're passing.
