### ISSUE TITLE
printf for Avian classpath

### ISSUE THREAD

**Issue by bgould** [ReadyTalk/avian#420]
Hi guys

I've been experimenting with Avian for the past few months and I've been quite pleased with the high quality of your work.

One thing I've found as a slight impediment is the inability to use some libraries unmodified because they make use of Java's printf/java.util.Formatter/etc.  This is generally pretty easy to work around but is annoying to maintain a fork of a library for such a small thing.

I've done a clean-room pure Java clone of java.util.Formatter... it is not 100% compatible but it will at least accept any of the format patterns specified in OpenJDK's java.util.Formatter.  I purposely have not looked at the source of any other implementations of this class so I am not sure how it stacks up performance-wise but I tried to minimize object allocation/memory usage as much as possible.  I would be glad to submit it as a pull request if you guys want to incorporate it into Avian classpath (I don't think I put it on Github yet but I will if you're interested), and I can add your preferred license to it if you do.

Questions I have though:

1) Is this something you guys might to include? :)
2) If so, what level of completeness would you require?  Certain formats just don't work yet... %s, %d, %x, width, zerofill, etc are working but some of the more esoteric ones are not.  The parser will gladly accept all valid patterns, it just doesn't output the formats properly.
3) Do you have a Contributor License Agreement or anything like that that I would need to sign?

The reason it is not on Github yet is that I have a bit of code cleanup to do before I publish it, and also the license I choose is dependent on what your preference would be.  The guts of the implementation is in 1 source file outside of the java.* namespaces, and I have an implementation of java.util.Formatter plus the format() and printf() methods to add to java.lang.String and java.io.PrintStream in order to integrate into Avian classpath.

Please let me know if you are interested and I will proceed accordingly.  Thanks for all your great work and your contributions to free software!

**Comment by dicej** [comment]
Hi BCG,

On Thu, 12 Mar 2015, BCG wrote:

> 1) Is this something you guys might to include? :)

Yes!

> 2) If so, what level of completeness would you require?  Certain formats 
> just don't work yet... %s, %d, %x, width, zerofill, etc are working but 
> some of the more esoteric ones are not.  The parser will gladly accept 
> all valid patterns, it just doesn't output the formats properly.

Whatever you have is fine.  Avian's class library will probably always be 
incomplete in various ways, and our philosophy has been to implement only 
the minimum necessary to get a given application working.  No point in 
doing extra work until you know you need it.

> 3) Do you have a Contributor License Agreement or anything like that 
> that I would need to sign?

Nope.

> The reason it is not on Github yet is that I have a bit of code cleanup 
> to do before I publish it, and also the license I choose is dependent on 
> what your preference would be.  The guts of the implementation is in 1 
> source file outside of the java.* namespaces, and I have an 
> implementation of java.util.Formatter plus the format() and printf() 
> methods to add to java.lang.String and java.io.PrintStream in order to 
> integrate into Avian classpath.

The license should be ISC like everything else in Avian 
(https://raw.githubusercontent.com/ReadyTalk/avian/master/license.txt). 
Also, we'd like to have at least some basic automated tests for features 
like this (see https://github.com/ReadyTalk/avian/tree/master/test for 
examples of tests of existing functionality).  Everything else you've 
described sounds fine to me.

> Please let me know if you are interested and I will proceed accordingly. 
> Thanks for all your great work and your contributions to free software!

Thank you for helping make it better!

**Comment by bgould** [comment]
Thanks, that sounds good to me. I have some tests like that already so I will include those. l'm shooting for getting things packaged up before the weekend.

**Comment by dicej** [comment]
Closing this issue since the patch has been merged.
