### ISSUE TITLE
Typo on main webpage

### ISSUE THREAD

**Issue by kirillseva** [ReadyTalk/avian#460]
Did not see a repo for the website. You've got a typo here: http://oss.readytalk.com/avian/

`lbrary`

**Comment by dicej** [comment]
Thanks.  It's fixed now:

https://github.com/ReadyTalk/avian-website/commit/69195f71af9d4aa13bc325237453b157c6028de7
https://github.com/ReadyTalk/avian/commit/d460e22c67748a049902f2f1b590aba83f5ceb6d
