### ISSUE TITLE
HTTP URLs cannot be opened. Sockets and BufferedInputStreamnot not working correctly.

### ISSUE THREAD

**Issue by keinhaar** [ReadyTalk/avian#467]
Hello,
i needed to use an HTTP URL for downloading some files. But this is not yet supported by the avian class library. So i did my own implementation of "avian/http/Handler.java", which may be useful for others too. It's just allowing to open an InputStream. NO OutputStreams, NO Proxy support and NO HTTPS or any other fancy stuff!!!
By trying to get this working, i found 2 Bugs related to read methods not being working correctly. One in java.net.Socket$SocketInputStream, and one in java.io.BufferedInputStream, which i fixed also. All of that is attached here.

[classpath.zip](https://github.com/ReadyTalk/avian/files/66763/classpath.zip)

Would be happy to see this 3 classes integrated into avian.
Thanks
Martin Schmitz

**Comment by dicej** [comment]
Hi Martin,

Thanks so much for working on this.  Would you mind submitting your changes as a pull request so I and others can more easily review and merge them?

**Comment by keinhaar** [comment]
I've never used git, but i think it's time to try...

**Comment by keinhaar** [comment]
OK, i've created an Pull Request. Hopefully this is usable for you. Otherwise let me know...
