### ISSUE TITLE
command shell instruction don't work

### ISSUE THREAD

**Issue by stax76** [ReadyTalk/avian#481]
Hello,

the make command gives an error

Frank@DESKTOP-EBTU8L3 MSYS /
$ make
make: *** There were not specified any targets and not "make" control file found. conclusion

**Comment by mesut146** [comment]
try "make platform=windows arch=x86_64"
change x86_64 to i386 if have 32 bit processor

**Comment by joshuawarner32** [comment]
@stax76 - Are you sure you're in the right directory?  It looks suspiciously like you current working directory is '/', which is presumably not where you have avian checked out.  You have to use 'cd' to change to the avian directory before issuing the make command.

**Comment by stax76** [comment]
thanks, now I have another problem and posted it at the google group
