### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by cubuspl42** [ReadyTalk/avian#488]
```
git clone git@github.com:ReadyTalk/win64.git ../win64
Cloning into '../win64'...
Permission denied (publickey).
fatal: Could not read from remote repository.
```

Platform: Win64, Cygwin (babun)

Cloning via HTTPS works.

**Comment by joshuawarner32** [comment]
I guess we naively assumed that developers will have their public keys set up with github - but we stand corrected! :)

You're right, https:// is a fine alternative.  That protocol used to be much less efficient than SSH, and has the downside of requiring username/password authentication (for private repos or if you want to push as a collaborator).  However, IIRC, there's a new active https:// git protocol that does basically what the git:// (i.e. ssh) protocol does (with all of the efficiency benefits) - and obviously wanting to push changes is not a problem for users in general.

Do you think we should change it in the readme?

**Comment by cubuspl42** [comment]
I have 10 SSH keys on github, but not for this machine... I thought that they are needed only for private repo access. I should've read the message more carefully, I guess.
HTTPS seems like a safe default, most people want things just work. =)
