### ISSUE TITLE
x86_64-w64-mingw32-g++: command not found

### ISSUE THREAD

**Issue by Programming4life** [ReadyTalk/avian#516]
I'm using msys2(Mingw Shell 32 bit), and I keep getting the error message below
`
/bin/sh: x86_64-w64-mingw32-g++: command not found
make: *** [makefile:1808: build/windows-x86_64/system/windows.o] Error 127
`

I've installed the gcc toolchain.
`
gcc version 6.2.0 (Rev2, Built by MSYS2 project)
`

**Comment by dscho** [comment]
> I've installed the gcc toolchain.

Since you use MSYS2, that statement cannot be correct: there are *multiple* GCC toolchains. The one you are most likely looking for is `mingw-w64-x86_64-toolchain` which you can install in MSYS2 using `pacman -Sy mingw-w64-x86_64-toolchain`.

**Comment by karencho777** [comment]
have the same issue but did not help post above
